/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tictactoe;

/**
 *
 * @author JGLop
 */
import java.awt.Color;


public final class MainScreen extends javax.swing.JFrame {
    
    
    private Jogo j;
    private Player p1;
    private Player p2;
    public static javax.swing.JButton buttons[];
    
    /**
     * Creates new form MainScreen
     */
    public MainScreen() {
        
        initComponents();
        MainScreen.buttons = new javax.swing.JButton[]{Tbtn1, Tbtn2, Tbtn3, Tbtn4, Tbtn5, Tbtn6, Tbtn7, Tbtn8, Tbtn9};
        starteed();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lbRound = new javax.swing.JLabel();
        lbWin = new javax.swing.JLabel();
        btnRerun = new javax.swing.JButton();
        Tbtn2 = new javax.swing.JButton();
        Tbtn3 = new javax.swing.JButton();
        Tbtn1 = new javax.swing.JButton();
        Tbtn5 = new javax.swing.JButton();
        Tbtn6 = new javax.swing.JButton();
        Tbtn4 = new javax.swing.JButton();
        Tbtn8 = new javax.swing.JButton();
        Tbtn9 = new javax.swing.JButton();
        Tbtn7 = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbRound.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbRound.setText("Round:");

        lbWin.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        lbWin.setText("Whinner:");

        btnRerun.setText("Reiniciar");
        btnRerun.setToolTipText("");
        btnRerun.setEnabled(false);
        btnRerun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRerunActionPerformed(evt);
            }
        });

        Tbtn2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn2.setText("jButton2");
        Tbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn2ActionPerformed(evt);
            }
        });

        Tbtn3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn3.setText("jButton2");
        Tbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn3ActionPerformed(evt);
            }
        });

        Tbtn1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn1.setText("jButton2");
        Tbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn1ActionPerformed(evt);
            }
        });

        Tbtn5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn5.setText("jButton2");
        Tbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn5ActionPerformed(evt);
            }
        });

        Tbtn6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn6.setText("jButton2");
        Tbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn6ActionPerformed(evt);
            }
        });

        Tbtn4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn4.setText("jButton2");
        Tbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn4ActionPerformed(evt);
            }
        });

        Tbtn8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn8.setText("jButton2");
        Tbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn8ActionPerformed(evt);
            }
        });

        Tbtn9.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn9.setText("jButton2");
        Tbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn9ActionPerformed(evt);
            }
        });

        Tbtn7.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Tbtn7.setText("jButton2");
        Tbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tbtn7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(lbWin, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48)
                .addComponent(lbRound, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Tbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Tbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Tbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(Tbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Tbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(241, 241, 241)
                        .addComponent(btnRerun, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbRound, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbWin, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tbtn2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tbtn5, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn6, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn4, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tbtn8, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn9, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tbtn7, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(64, 64, 64)
                .addComponent(btnRerun, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRerunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRerunActionPerformed
        j.iniciar(p1, p2);
    }//GEN-LAST:event_btnRerunActionPerformed

    private void Tbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn2ActionPerformed
        
        Tbtn2.setText(Character.toString(j.round.simb));
        button_pressed(0,1);
    }//GEN-LAST:event_Tbtn2ActionPerformed

    private void Tbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn3ActionPerformed
        
        Tbtn3.setText(Character.toString(j.round.simb));
        button_pressed(0,2);
    }//GEN-LAST:event_Tbtn3ActionPerformed

    private void Tbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn1ActionPerformed

        
        Tbtn1.setText(Character.toString(j.round.simb));
        button_pressed(0,0);
    }//GEN-LAST:event_Tbtn1ActionPerformed

    private void Tbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn5ActionPerformed
        
        Tbtn5.setText(Character.toString(j.round.simb));
        button_pressed(1,1);
    }//GEN-LAST:event_Tbtn5ActionPerformed

    private void Tbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn6ActionPerformed
        
        Tbtn6.setText(Character.toString(j.round.simb));
        button_pressed(1,2);
    }//GEN-LAST:event_Tbtn6ActionPerformed

    private void Tbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn4ActionPerformed
        
        Tbtn4.setText(Character.toString(j.round.simb));
        button_pressed(1,0);
    }//GEN-LAST:event_Tbtn4ActionPerformed

    private void Tbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn8ActionPerformed
        
        Tbtn8.setText(Character.toString(j.round.simb));
        button_pressed(2,1);
    }//GEN-LAST:event_Tbtn8ActionPerformed

    private void Tbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn9ActionPerformed
        
        Tbtn9.setText(Character.toString(j.round.simb));
        button_pressed(2,2);
    }//GEN-LAST:event_Tbtn9ActionPerformed

    private void Tbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tbtn7ActionPerformed
        
        Tbtn7.setText(Character.toString(j.round.simb));
        button_pressed(2,0);
    }//GEN-LAST:event_Tbtn7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainScreen().setVisible(true);
                
            }
            
        });
        
      
        
    }
    
    public void starteed() {
        j = new Jogo();
        p1 = new Player(j);
        p2 = new Player(j);
        
        j.iniciar(p1,p2);
        
        btnRerun.setVisible(false);
    }
    
    private void button_pressed(int x, int y){
        j.round.marcar(x, y);
        lbRound.setText("Round: " + j.round.nome);
        
  
    };


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton Tbtn1;
    public static javax.swing.JButton Tbtn2;
    public static javax.swing.JButton Tbtn3;
    public static javax.swing.JButton Tbtn4;
    public static javax.swing.JButton Tbtn5;
    public static javax.swing.JButton Tbtn6;
    public static javax.swing.JButton Tbtn7;
    public static javax.swing.JButton Tbtn8;
    public static javax.swing.JButton Tbtn9;
    public static javax.swing.JButton btnRerun;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel lbRound;
    public static javax.swing.JLabel lbWin;
    // End of variables declaration//GEN-END:variables


    
}
